name: mindsolver_flutter

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  table_calendar: ^3.0.9
  fluttertoast: ^8.2.4

  # firebase
  firebase_core: ^2.24.2
  firebase_core_platform_interface: ^5.0.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  google_sign_in: ^6.2.1
  
  eventsource: ^0.4.0
  image_picker: ^1.0.7
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - icons/

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Regular.otf
        - asset: fonts/Pretendard-SemiBold.otf