name: mindsolver_flutter

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  firebase_core: ^2.24.2
  firebase_core_platform_interface: ^5.0.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - icons/
